### ISSUE TITLE
ESP32: Telnet / FHEM not working  

### ISSUE THREAD

**Issue by sidey79** [HomeAutoUser/cc1101_rf_Gateway#4]
Telnet client can connect, but get no response:

FHEM logfile
```
2024.01.03 22:49:42 5: signalESP_2: SimpleWrite, V
2024.01.03 22:49:42 3: signalESP_2: StartInit, get version, retry = 2
2024.01.03 22:49:42 1: signalESP_2: CheckVersionResp, Not an SIGNALduino device, got for V: undef
2024.01.03 22:49:42 5: signalESP_2: CheckVersionResp, called without msg
2024.01.03 22:49:32 5: signalESP_2: SimpleWrite, V
2024.01.03 22:49:32 3: signalESP_2: StartInit, get version, retry = 1
2024.01.03 22:49:32 1: signalESP_2: CheckVersionResp, Not an SIGNALduino device, got for V: undef
2024.01.03 22:49:32 5: signalESP_2: CheckVersionResp, called without msg
2024.01.03 22:49:22 5: signalESP_2: SimpleWrite, V
```

Der client ist allerdings connected cc1101_rf_Gateway logfile

```
2024-01-03 23:03:47 - Telnet client 10.2.11.2 connected
```

Mittels telnet manuell geht es auch nicht :(

**Comment by HomeAutoUser** [comment]
Check:
- kannst du auf die Oberfläche zugreifen im Browser?
- kannst du dich direkt mit dem uC verbinden und ein Kommando absetzen?

**Comment by sidey79** [comment]
Die Weboberfläche funktioniert,
aber manuell Kommandos über telnet geht nicht.

**Comment by HomeAutoUser** [comment]
Wie sind die Ausgaben in diesem Fenster?
https://github.com/HomeAutoUser/cc1101_rf_Gateway?tab=readme-ov-file#pictures-from-version-1015--reception-can-be-compiled-differently

Wichtig: 
- Firmware mode -> muss FHEM compatible sein
- Version

**Comment by sidey79** [comment]
Firmware mode war FHEM compatible :)

Hab jetzt erst mal SIGNALDUINO FW geflasht um zu prüfen, dass es nicht an der Hardware oder Verkabelung oder sowas liegt, aber da geht das Telnet Kommando direkt :)

**Comment by sidey79** [comment]
<html>
<body>

Device - Information
--
Firmware compiled | Jan 4 2024 11:29:16
Firmware mode | FHEM compatible
Message count | 0RESET Counter
RAM (free heap) | 223376
RSSI (WLAN connection) | -76 dB
Uptime (Seconds) | 12RESTART ESP
Uptime (Text) | 0 day(s) 0 hour(s) 0 minute(s) 12 second(s)
Version | V 1.0.17 SIGNALduino compatible cc1101_rf_Gateway (2023-12-20)


</body>
</html>

**Comment by sidey79** [comment]
Sobald ich über Telnet einen Befehl absetze erscheint im Debug noch folgende Ausgabe

`DB Telnet, Data from session 0`

Danach hängt der ESP. Ich vermute er hängt in einer Schleife fest, denn es reagiert danach das Web Interface nicht mehr

**Comment by sidey79** [comment]
Der Prozess hängt nachweislich hier:

[        msg = TelnetClient[i].readString();
](https://github.com/HomeAutoUser/cc1101_rf_Gateway/blob/1bad1488b5174b4cc00837f832197ed7e51296b6/src/arduino-ide/cc1101_rf/cc1101_rf.ino#L1660)

Mit readString habe ich bisher auch nie gearbeitet. Dokus finden sich dazu recht wenig in Verbindung mit dem wificlient.

**Comment by sidey79** [comment]
Kleines Update, wenn man so gefühlte 5 Minuten wartet wird das Kommando beantwortet:

```
DB InputCommand, String V
DB InputCommand [0] = V
V 1.0.17 SIGNALduino compatible cc1101_rf_Gateway (2023-12-20) Jan  4 2024 13:35:54
```

**Comment by HomeAutoUser** [comment]
Danke für deine Mühe. Ich habe heute auch nochmal nachgesehen und wie der Zufall wollte, schlich sich bei deinem uC ein Fehler ein. Wir haben die Stelle lokalisiert.

PS: Sorry für den voreiligen Hinweis und das du dadurch in unsere Fehlersuche "geschoben" wurdest *smile*

**Comment by HomeAutoUser** [comment]
> Der Prozess hängt nachweislich hier:
> 
> [ msg = TelnetClient[i].readString(); ](https://github.com/HomeAutoUser/cc1101_rf_Gateway/blob/1bad1488b5174b4cc00837f832197ed7e51296b6/src/arduino-ide/cc1101_rf/cc1101_rf.ino#L1660)
> 
> Mit readString habe ich bisher auch nie gearbeitet. Dokus finden sich dazu recht wenig in Verbindung mit dem wificlient.

Das ist der Knackpunkt.
Mit dem ESP8266 geht das aber bei dem ES32 auf einmal nicht mehr. Wir werden dies an der stelle vermutlich anders lösen.

**Comment by sidey79** [comment]
Ja, das sind die fiesen Feinheiten, dass bei einem uC auf einmal was nicht so geht wie es sollte.

**Comment by sidey79** [comment]
Mit meinem ursprünglichen Problem bin ich leider auch nicht weiter gekommen.
Ich habe jetzt zwei esp32 mit cc1101 und wenn ich was (FSK) sende , dann empfängt der andere nichts.

**Comment by HomeAutoUser** [comment]
> Mit meinem ursprünglichen Problem bin ich leider auch nicht weiter gekommen. Ich habe jetzt zwei esp32 mit cc1101 und wenn ich was (FSK) sende , dann empfängt der andere nichts.

Wir ist dein genauer Aufbau und mit welcher Firmware?
2 Signalduinos?

**Comment by sidey79** [comment]
Zwei esp32 jeder ein cc1101.

Der eine hat das 868 Modul, der andere ein 433 Modul.

Dass es mit dem 433 Modul nicht optimale ist, weiss ich, aber damit emfpange ich auch WH40 Sensoren.
Grundsätzlich funktioniert der Empfangsteil.

Gesendet und empfangen habe ich mit der Signalduino FW und auch mit dem Gateway hier.

Aber der andere Empfänger bekommt davon nichts mit.
Signalduino FW habe ich auch schon geprüft und angepasst, aber ich nehme an, der cc1101 sendet wenn er was in den FiFo gelegt bekommt.

**Comment by HomeAutoUser** [comment]
Das kommt mir irgendwie bekannt vor.

> Der eine hat das 868 Modul, der andere ein 433 Modul.

> Dass es mit dem 433 Modul nicht optimale ist, weiss ich, aber damit emfpange ich auch WH40 Sensoren.
Grundsätzlich funktioniert der Empfangsteil.

Stelle mal bitte den 868er auf 433 und sende dann mal. Von deiner Zusammenstellung habe ich auch schlechte Erfahrungen gemacht. Zum Schluss habe ich immer nur 100% Erfolge erzielt wenn ich mit je 2 gleichen Modulen getestet habe.
Bestes Beispiel sind die Lacrosse Sensoren. Diese habe ich auch nicht mit einem 433er auf 868Mhz eingestellt empfangen.

PS: ich bin schon schlauer was den fix im cc1101_Gateyway angeht.

**Comment by sidey79** [comment]
> Stelle mal bitte den 868er auf 433 und sende dann mal. Von deiner Zusammenstellung habe ich auch schlechte Erfahrungen gemacht. Zum Schluss habe ich immer nur 100% Erfolge erzielt wenn ich mit je 2 gleichen Modulen getestet habe. Bestes Beispiel sind die Lacrosse Sensoren. Diese habe ich auch nicht mit einem 433er auf 868Mhz eingestellt empfangen.

Hmm, also auf 433 Mhz geht es im SlowRF mode.
Dummerweise habe ich kein zweites intaktes 868 Modul :(

Senden will ich ja auch nur, weil ich die PCA301 anlernen muss, aber das klappt nicht. 

> PS: ich bin schon schlauer was den fix im cc1101_Gateyway angeht.

Okay, ich kann dann testen wenn Du was hast :)

**Comment by HomeAutoUser** [comment]
Hier gibt es schon eine Anpassung wo der ESP32 funktioniert.
https://github.com/HomeAutoUser/cc1101_rf_Gateway/tree/pre-release

Bist du denn weiter gekommen mit deinem Vorhaben? @sidey79

**Comment by sidey79** [comment]
Mit den PCA301 Dosen bin ich leider nicht weiter gekommen, ich habe mir erst mal mit einer Tasmota Dose beholfen.

**Comment by sidey79** [comment]
<img width="814" alt="image" src="https://github.com/HomeAutoUser/cc1101_rf_Gateway/assets/7968127/b9c6e42c-5dfb-43ec-a223-009ea6cde666">

Funktioniert

**Comment by sidey79** [comment]
@HomeAutoUser 

Eventuell habe ich eines der schlechten Module mit abweichendem Quarz:
https://forum.fhem.de/index.php?topic=91740.225


So eine Art Frequenzscan wäre nicht schlecht.
Habe auch überlegt, ob man das in FHEM einbauen könnte. Quasi immer 10 Minuten auf einer Frequenz bleiben und dann ab zur Nächsten und warten bis was kommt.

**Comment by HomeAutoUser** [comment]
> So eine Art Frequenzscan wäre nicht schlecht. Habe auch überlegt, ob man das in FHEM einbauen könnte. Quasi immer 10 Minuten auf einer Frequenz bleiben und dann ab zur Nächsten und warten bis was kommt.

@sidey79 
diese Möglichkeit besteht mit dem TOOL von uns. Da kannst du ein IODev einstellen und Start|End Frequenz / Frequenzsprünge und Zeit. Nach dem Scan stehen die Ergebnisse in einer Textdatei zur Einsicht.

**Comment by sidey79** [comment]
Muss ich mir dann noch mal ansehen, habe es mit einem doif realisiert aber nichts empfangen.
